### ISSUE TITLE
Vim

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/learning#2]

**Comment by Widdershin** [comment]
Josh gave an intro at the Learning Bee. Should check out @joshuavial's dotfiles

**Comment by joshuavial** [comment]
https://github.com/joshuavial/dotfiles/blob/master/vimrc

**Comment by Widdershin** [comment]
Ran through vimtutor. Got set up with josh's vimrc and trying vim out as editor of choice.

**Comment by Widdershin** [comment]
Feeling happy with the basics.

My setup:

![Imgur](http://i.imgur.com/CEmd7gA.png)

Tracking more vim learning in #9
